### ISSUE TITLE
Invalid when statement with jinja tags

### ISSUE THREAD

**Issue by DelphicOkami** [Oefenweb/ansible-sysfs#2]
On ansible 2.4.2.0 when I run a playbook containing this role I get the error:
``[WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: {{ sysfs_uses_old_sysfsutils | bool == true }}``

I believe this is caused on [Line 62 of the tasks file](https://github.com/Oefenweb/ansible-sysfs/blob/c65e99c1a58fa5dd527724d881f6d19469844763/tasks/main.yml#L62)

**Comment by tersmitten** [comment]
Fixed
